services:
  db:
    image: cauebaia/carteira-db:1.0.1
    container_name: carteira_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: wallet_api_homolog
      POSTGRES_PASSWORD: api123
      POSTGRES_DB: wallet_homolog
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: cauebaia/carteira-api:1.0.1
    container_name: carteira_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wallet_api_homolog
      DB_PASSWORD: api123
      DB_NAME: wallet_homolog
    ports:
      - "8000:8000"

volumes:
  postgres_data:
